version: '3.7'
services:
  web:
    image: sunnywalden/service-healthcheck-metrics:latest
    container_name: service_healthcheck
    ports:
      - "8000:8000"
    environment:
      ENV_TYPE: prod
      EXTERNAL: "false"
    volumes:
      - /data/healthcheck_metrics/configs/:/opt/application/healthcheck_metrics/configs/
    networks:
      - service_healthcheck
    restart: always

networks:
  service_healthcheck:
    driver: bridge