version: '3.7'
services:
  web:
    image: sunnywalden/service-healthcheck-exporter:latest
    container_name: service_healthcheck
    ports:
      - "8000:8000"
    environment:
      ENV_TYPE: prod
      EXTERNAL: False
    volumes:
      - /data/healthcheck_exporter/configs/:/opt/application/healthcheck_exporter/configs/
    networks:
      - service_healthcheck
    restart: always

networks:
  service_healthcheck:
    driver: bridge