version: '3.7'
services:
  web:
    image: sunnywalden/service-healthcheck-metrics:latest
    container_name: service_healthcheck
    ports:
      - "8000:8080"
    environment:
      ENV_TYPE: prod
      EXTERNAL: "false"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080"/, "||", "exit", "1"]
      interval: 2m
      timeout: 10s
      retries: 3
    volumes:
      - /data/healthcheck_metrics/configs/:/opt/application/healthcheck_metrics/configs/
    networks:
      - service_healthcheck
    restart: always

networks:
  service_healthcheck:
    driver: bridge